# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Clémence\Documents\0-ENSG\1_TRONC_COMMUN\PROJET_INFO\1_ANALYSE\active-labelling\interface\chargementFichiers.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import strategy

class Ui_ChargerFichier(object):
    def setupUi(self, ChargerFichier):
        ChargerFichier.setObjectName("ChargerFichier")
        ChargerFichier.resize(676, 493)
        self.gridLayout = QtWidgets.QGridLayout(ChargerFichier)
        self.gridLayout.setObjectName("gridLayout")
        self.chargerEmpriseButton = QtWidgets.QPushButton(ChargerFichier)
        self.chargerEmpriseButton.setObjectName("chargerEmpriseButton")
        self.gridLayout.addWidget(self.chargerEmpriseButton, 7, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 6, 1, 4)
        self.resultLabel = QtWidgets.QLabel(ChargerFichier)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.resultLabel.setFont(font)
        self.resultLabel.setObjectName("resultLabel")
        self.gridLayout.addWidget(self.resultLabel, 5, 2, 1, 1)
        self.chargerResultButton = QtWidgets.QPushButton(ChargerFichier)
        self.chargerResultButton.setObjectName("chargerResultButton")
        self.gridLayout.addWidget(self.chargerResultButton, 5, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 4, 1, 1)
        self.chargerClasseButton = QtWidgets.QPushButton(ChargerFichier)
        self.chargerClasseButton.setObjectName("chargerClasseButton")
        self.gridLayout.addWidget(self.chargerClasseButton, 3, 4, 1, 1)
        self.orthoLabel = QtWidgets.QLabel(ChargerFichier)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.orthoLabel.setFont(font)
        self.orthoLabel.setObjectName("orthoLabel")
        self.gridLayout.addWidget(self.orthoLabel, 9, 2, 1, 1)
        self.classeLabel = QtWidgets.QLabel(ChargerFichier)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.classeLabel.setFont(font)
        self.classeLabel.setObjectName("classeLabel")
        self.gridLayout.addWidget(self.classeLabel, 3, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 4, 4, 1, 1)
        self.chargerOrthoButton = QtWidgets.QPushButton(ChargerFichier)
        self.chargerOrthoButton.setObjectName("chargerOrthoButton")
        self.gridLayout.addWidget(self.chargerOrthoButton, 9, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 4, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 0, 0, 1, 11)
        self.chargLabel = QtWidgets.QLabel(ChargerFichier)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.chargLabel.setFont(font)
        self.chargLabel.setObjectName("chargLabel")
        self.gridLayout.addWidget(self.chargLabel, 1, 0, 1, 6)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 14, 2, 1, 3)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 16, 8, 2, 1)
        self.paramLabel = QtWidgets.QLabel(ChargerFichier)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.paramLabel.setFont(font)
        self.paramLabel.setObjectName("paramLabel")
        self.gridLayout.addWidget(self.paramLabel, 11, 0, 1, 3)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 1, 10, 18, 1)
        self.nbrEdit = QtWidgets.QLineEdit(ChargerFichier)
        self.nbrEdit.setEnabled(False)
        self.nbrEdit.setObjectName("nbrEdit")
        self.gridLayout.addWidget(self.nbrEdit, 14, 8, 1, 1)
        self.affichLabel = QtWidgets.QLabel(ChargerFichier)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.affichLabel.setFont(font)
        self.affichLabel.setObjectName("affichLabel")
        self.gridLayout.addWidget(self.affichLabel, 16, 2, 1, 1)
        self.nbrLabel = QtWidgets.QLabel(ChargerFichier)
        self.nbrLabel.setEnabled(False)
        self.nbrLabel.setObjectName("nbrLabel")
        self.gridLayout.addWidget(self.nbrLabel, 14, 5, 1, 3)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 15, 2, 1, 7)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 12, 0, 1, 7)
        self.margeXEdit = QtWidgets.QLineEdit(ChargerFichier)
        self.margeXEdit.setObjectName("margeXEdit")
        self.gridLayout.addWidget(self.margeXEdit, 16, 5, 1, 3)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 13, 4, 1, 1)
        self.modeComboBox = QtWidgets.QComboBox(ChargerFichier)
        self.modeComboBox.setObjectName("modeComboBox")
        self.gridLayout.addWidget(self.modeComboBox, 13, 5, 1, 4)
        self.empriseLabel = QtWidgets.QLabel(ChargerFichier)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.empriseLabel.setFont(font)
        self.empriseLabel.setObjectName("empriseLabel")
        self.gridLayout.addWidget(self.empriseLabel, 7, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(ChargerFichier)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 13, 1, 5, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 8, 4, 1, 1)
        self.cheminEmpriseLabel = QtWidgets.QLabel(ChargerFichier)
        self.cheminEmpriseLabel.setObjectName("cheminEmpriseLabel")
        self.gridLayout.addWidget(self.cheminEmpriseLabel, 7, 6, 1, 4)
        self.margeYEdit = QtWidgets.QLineEdit(ChargerFichier)
        self.margeYEdit.setObjectName("margeYEdit")
        self.gridLayout.addWidget(self.margeYEdit, 17, 5, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(ChargerFichier)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 19, 1, 1, 10)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem13, 2, 0, 1, 7)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem14, 6, 2, 1, 1)
        self.margeYLabel = QtWidgets.QLabel(ChargerFichier)
        self.margeYLabel.setObjectName("margeYLabel")
        self.gridLayout.addWidget(self.margeYLabel, 17, 3, 1, 2)
        self.margeXLabel = QtWidgets.QLabel(ChargerFichier)
        self.margeXLabel.setObjectName("margeXLabel")
        self.gridLayout.addWidget(self.margeXLabel, 16, 3, 1, 2)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem15, 8, 6, 1, 4)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem16, 10, 2, 1, 6)
        self.modeLabel = QtWidgets.QLabel(ChargerFichier)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.modeLabel.setFont(font)
        self.modeLabel.setObjectName("modeLabel")
        self.gridLayout.addWidget(self.modeLabel, 13, 2, 1, 2)
        self.chemClasseLabel = QtWidgets.QLabel(ChargerFichier)
        self.chemClasseLabel.setObjectName("chemClasseLabel")
        self.gridLayout.addWidget(self.chemClasseLabel, 3, 6, 1, 4)
        self.cheminResultLabel = QtWidgets.QLabel(ChargerFichier)
        self.cheminResultLabel.setObjectName("cheminResultLabel")
        self.gridLayout.addWidget(self.cheminResultLabel, 5, 6, 1, 4)
        self.cheminOrthoLabel = QtWidgets.QLabel(ChargerFichier)
        self.cheminOrthoLabel.setObjectName("cheminOrthoLabel")
        self.gridLayout.addWidget(self.cheminOrthoLabel, 9, 6, 1, 4)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem17, 3, 3, 7, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem18, 18, 0, 1, 10)
        self.line = QtWidgets.QFrame(ChargerFichier)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 1, 7, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem19, 6, 6, 1, 4)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem20, 13, 9, 2, 1)

        self.retranslateUi(ChargerFichier)
        self.buttonBox.accepted.connect(ChargerFichier.accept)
        self.buttonBox.rejected.connect(ChargerFichier.reject)
        QtCore.QMetaObject.connectSlotsByName(ChargerFichier)

    def retranslateUi(self, ChargerFichier):
        _translate = QtCore.QCoreApplication.translate
        ChargerFichier.setWindowTitle(_translate("ChargerFichier", "Chargement des fichiers"))
        self.chargerEmpriseButton.setText(_translate("ChargerFichier", "Charger..."))
        self.resultLabel.setText(_translate("ChargerFichier", "Résultat de classification"))
        self.chargerResultButton.setText(_translate("ChargerFichier", "Charger..."))
        self.chargerClasseButton.setText(_translate("ChargerFichier", "Charger..."))
        self.orthoLabel.setText(_translate("ChargerFichier", "Orthoimage"))
        self.classeLabel.setText(_translate("ChargerFichier", "Description des classes"))
        self.chargerOrthoButton.setText(_translate("ChargerFichier", "Charger..."))
        self.chargLabel.setText(_translate("ChargerFichier", "Chargement des fichiers"))
        self.paramLabel.setText(_translate("ChargerFichier", "Paramètres de traitement"))
        self.nbrEdit.setText(_translate("ChargerFichier", "3"))
        self.affichLabel.setText(_translate("ChargerFichier", "Affichage"))
        self.nbrLabel.setText(_translate("ChargerFichier", "Nombre d\'entités à afficher :"))
        self.margeXEdit.setText(_translate("ChargerFichier", "50"))
        self.empriseLabel.setText(_translate("ChargerFichier", "Dossier des emprises"))
        self.cheminEmpriseLabel.setText(_translate("ChargerFichier", "[CheminEmprise]"))
        self.margeYEdit.setText(_translate("ChargerFichier", "50"))
        self.margeYLabel.setText(_translate("ChargerFichier", "Marge horizontale"))
        self.margeXLabel.setText(_translate("ChargerFichier", "Marge verticale"))
        self.modeLabel.setText(_translate("ChargerFichier", "Mode de sélection des entités"))
        self.chemClasseLabel.setText(_translate("ChargerFichier", "[CheminClasses]"))
        self.cheminResultLabel.setText(_translate("ChargerFichier", "[CheminResultats]"))
        self.cheminOrthoLabel.setText(_translate("ChargerFichier", "[CheminOrtho]"))

        # Affiche les strategies dans la ComboBox
        self.modeComboBox.addItems([str(i) for i in strategy.STRATEGIES])
