# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Clémence\Documents\0-ENSG\1_TRONC_COMMUN\PROJET_INFO\1_ANALYSE\active-labelling\interface\classificationActive.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InterfacePrincipale(object):
    def setupUi(self, InterfacePrincipale):
        InterfacePrincipale.setObjectName("InterfacePrincipale")
        InterfacePrincipale.resize(1003, 679)
        InterfacePrincipale.setMinimumSize(QtCore.QSize(900, 650))
        InterfacePrincipale.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.centralwidget = QtWidgets.QWidget(InterfacePrincipale)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 4, 3, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 11, 1, 3)
        self.questionLabel = QtWidgets.QLabel(self.centralwidget)
        self.questionLabel.setObjectName("questionLabel")
        self.gridLayout.addWidget(self.questionLabel, 3, 5, 1, 4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 16)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 19, 1)
        self.probaLabel = QtWidgets.QLabel(self.centralwidget)
        self.probaLabel.setObjectName("probaLabel")
        self.gridLayout.addWidget(self.probaLabel, 7, 7, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 3, 1, 12)
        spacerItem5 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 8, 3, 2, 12)
        self.classeLabel = QtWidgets.QLabel(self.centralwidget)
        self.classeLabel.setObjectName("classeLabel")
        self.gridLayout.addWidget(self.classeLabel, 6, 7, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 6, 3, 1)
        self.yesButton = QtWidgets.QPushButton(self.centralwidget)
        self.yesButton.setObjectName("yesButton")
        self.gridLayout.addWidget(self.yesButton, 10, 4, 1, 11)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 11, 3, 1, 12)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 13, 3, 1, 12)
        self.idLabel = QtWidgets.QLabel(self.centralwidget)
        self.idLabel.setObjectName("idLabel")
        self.gridLayout.addWidget(self.idLabel, 5, 7, 1, 1)
        self.noButton = QtWidgets.QPushButton(self.centralwidget)
        self.noButton.setObjectName("noButton")
        self.gridLayout.addWidget(self.noButton, 12, 4, 1, 11)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 18, 1, 1, 14)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 3, 4, 1, 1)
        self.helpLogo = QtWidgets.QLabel(self.centralwidget)
        self.helpLogo.setMaximumSize(QtCore.QSize(20, 20))
        self.helpLogo.setText("")
        self.helpLogo.setPixmap(QtGui.QPixmap("question.png"))
        self.helpLogo.setScaledContents(True)
        self.helpLogo.setObjectName("helpLogo")
        self.gridLayout.addWidget(self.helpLogo, 6, 11, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 1, 15, 19, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 4, 3, 1, 12)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 15, 4, 3, 2)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 15, 8, 3, 2)
        self.borneyValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.borneyValueLabel.setObjectName("borneyValueLabel")
        self.gridLayout.addWidget(self.borneyValueLabel, 17, 11, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 16, 10, 2, 1)
        self.borneLabel = QtWidgets.QLabel(self.centralwidget)
        self.borneLabel.setObjectName("borneLabel")
        self.gridLayout.addWidget(self.borneLabel, 16, 7, 1, 1)
        self.bornexValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.bornexValueLabel.setObjectName("bornexValueLabel")
        self.gridLayout.addWidget(self.bornexValueLabel, 16, 11, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 7, 11, 1, 3)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 6, 12, 1, 2)
        self.entiteView = QtWidgets.QGraphicsView(self.centralwidget)
        self.entiteView.setMinimumSize(QtCore.QSize(500, 400))
        self.entiteView.setMaximumSize(QtCore.QSize(1500, 1500))
        self.entiteView.setObjectName("entiteView")
        self.gridLayout.addWidget(self.entiteView, 1, 1, 17, 2)
        InterfacePrincipale.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(InterfacePrincipale)
        self.menuBar.setEnabled(True)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1003, 26))
        self.menuBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menuBar.setDefaultUp(False)
        self.menuBar.setObjectName("menuBar")
        self.fichierMenu = QtWidgets.QMenu(self.menuBar)
        self.fichierMenu.setObjectName("fichierMenu")
        InterfacePrincipale.setMenuBar(self.menuBar)
        self.statusbar = QtWidgets.QStatusBar(InterfacePrincipale)
        self.statusbar.setObjectName("statusbar")
        InterfacePrincipale.setStatusBar(self.statusbar)
        self.chargerAction = QtWidgets.QAction(InterfacePrincipale)
        self.chargerAction.setObjectName("chargerAction")
        self.fichierMenu.addAction(self.chargerAction)
        self.menuBar.addAction(self.fichierMenu.menuAction())

        self.retranslateUi(InterfacePrincipale)
        QtCore.QMetaObject.connectSlotsByName(InterfacePrincipale)

    def retranslateUi(self, InterfacePrincipale):
        _translate = QtCore.QCoreApplication.translate
        InterfacePrincipale.setWindowTitle(_translate("InterfacePrincipale", "Classification active"))
        self.questionLabel.setText(_translate("InterfacePrincipale", "Cet objet est il bien classé ?"))
        self.probaLabel.setText(_translate("InterfacePrincipale", "Probabilité"))
        self.classeLabel.setText(_translate("InterfacePrincipale", "Classe"))
        self.yesButton.setText(_translate("InterfacePrincipale", "OUI"))
        self.idLabel.setText(_translate("InterfacePrincipale", "Identifiant de l\'objet"))
        self.noButton.setText(_translate("InterfacePrincipale", "NON"))
        self.borneyValueLabel.setText(_translate("InterfacePrincipale", "(xmax, ymax)"))
        self.borneLabel.setText(_translate("InterfacePrincipale", "Bornes d\'affichage"))
        self.bornexValueLabel.setText(_translate("InterfacePrincipale", "(xmin, ymin)"))
        self.fichierMenu.setTitle(_translate("InterfacePrincipale", "Fichier"))
        self.chargerAction.setText(_translate("InterfacePrincipale", "Charger ..."))

#import images_rc
