# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Clémence\Documents\0-ENSG\1_TRONC_COMMUN\PROJET_INFO\1_ANALYSE\active-labelling\interface\activeLabelling.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_activeLabelling(object):
    def setupUi(self, activeLabelling):
        activeLabelling.setObjectName("activeLabelling")
        activeLabelling.resize(854, 475)
        self.widget = QtWidgets.QWidget(activeLabelling)
        self.widget.setGeometry(QtCore.QRect(30, 30, 791, 411))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.fenetreGraphique = QtWidgets.QGraphicsView(self.widget)
        self.fenetreGraphique.setMinimumSize(QtCore.QSize(401, 401))
        self.fenetreGraphique.setObjectName("fenetreGraphique")
        self.gridLayout.addWidget(self.fenetreGraphique, 1, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.questionText = QtWidgets.QLabel(self.widget)
        self.questionText.setObjectName("questionText")
        self.verticalLayout_3.addWidget(self.questionText)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.idText = QtWidgets.QLabel(self.widget)
        self.idText.setObjectName("idText")
        self.horizontalLayout_3.addWidget(self.idText)
        spacerItem3 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.idBox = QtWidgets.QTextEdit(self.widget)
        self.idBox.setObjectName("idBox")
        self.horizontalLayout_3.addWidget(self.idBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.classeText = QtWidgets.QLabel(self.widget)
        self.classeText.setObjectName("classeText")
        self.horizontalLayout_2.addWidget(self.classeText)
        spacerItem6 = QtWidgets.QSpacerItem(58, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.classeBox = QtWidgets.QTextEdit(self.widget)
        self.classeBox.setObjectName("classeBox")
        self.horizontalLayout_2.addWidget(self.classeBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.probText = QtWidgets.QLabel(self.widget)
        self.probText.setObjectName("probText")
        self.horizontalLayout.addWidget(self.probText)
        spacerItem9 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.probBox = QtWidgets.QTextEdit(self.widget)
        self.probBox.setObjectName("probBox")
        self.horizontalLayout.addWidget(self.probBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.yesButton = QtWidgets.QPushButton(self.widget)
        self.yesButton.setObjectName("yesButton")
        self.verticalLayout_2.addWidget(self.yesButton)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem11)
        self.noButton = QtWidgets.QPushButton(self.widget)
        self.noButton.setObjectName("noButton")
        self.verticalLayout_2.addWidget(self.noButton)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.idText.raise_()
        self.classeText.raise_()
        self.probText.raise_()
        self.yesButton.raise_()
        self.noButton.raise_()
        self.questionText.raise_()
        self.classeBox.raise_()
        self.idBox.raise_()
        self.probBox.raise_()
        self.questionText.raise_()

        self.retranslateUi(activeLabelling)
        QtCore.QMetaObject.connectSlotsByName(activeLabelling)

    def retranslateUi(self, activeLabelling):
        _translate = QtCore.QCoreApplication.translate
        activeLabelling.setWindowTitle(_translate("activeLabelling", "Interface de classification"))
        self.questionText.setText(_translate("activeLabelling", "Cet objet est-t-il bien classé ?"))
        self.idText.setText(_translate("activeLabelling", "Identifiant :"))
        self.classeText.setText(_translate("activeLabelling", "Classe :"))
        self.probText.setText(_translate("activeLabelling", "Probabilité :"))
        self.yesButton.setText(_translate("activeLabelling", "Oui"))
        self.noButton.setText(_translate("activeLabelling", "Non"))

