# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Clémence\Documents\0-ENSG\1_TRONC_COMMUN\PROJET_INFO\1_ANALYSE\active-labelling\interface\chargementFichiers.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ChargerFichier(object):
    def setupUi(self, ChargerFichier):
        ChargerFichier.setObjectName("ChargerFichier")
        ChargerFichier.resize(561, 300)
        self.gridLayout = QtWidgets.QGridLayout(ChargerFichier)
        self.gridLayout.setObjectName("gridLayout")
        self.classLabel = QtWidgets.QLabel(ChargerFichier)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.classLabel.setFont(font)
        self.classLabel.setObjectName("classLabel")
        self.gridLayout.addWidget(self.classLabel, 1, 2, 1, 1)
        self.cheminEmpriseLabel = QtWidgets.QLabel(ChargerFichier)
        self.cheminEmpriseLabel.setObjectName("cheminEmpriseLabel")
        self.gridLayout.addWidget(self.cheminEmpriseLabel, 5, 6, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 7, 8, 1)
        self.cheminOrthoLabel = QtWidgets.QLabel(ChargerFichier)
        self.cheminOrthoLabel.setObjectName("cheminOrthoLabel")
        self.gridLayout.addWidget(self.cheminOrthoLabel, 7, 6, 1, 1)
        self.cheminResultLabel = QtWidgets.QLabel(ChargerFichier)
        self.cheminResultLabel.setObjectName("cheminResultLabel")
        self.gridLayout.addWidget(self.cheminResultLabel, 3, 6, 1, 1)
        self.chargerEmprButton = QtWidgets.QPushButton(ChargerFichier)
        self.chargerEmprButton.setObjectName("chargerEmprButton")
        self.gridLayout.addWidget(self.chargerEmprButton, 5, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 5, 7, 1)
        self.chargerOrthoButton = QtWidgets.QPushButton(ChargerFichier)
        self.chargerOrthoButton.setObjectName("chargerOrthoButton")
        self.gridLayout.addWidget(self.chargerOrthoButton, 7, 4, 1, 1)
        self.chargerResultButton = QtWidgets.QPushButton(ChargerFichier)
        self.chargerResultButton.setObjectName("chargerResultButton")
        self.gridLayout.addWidget(self.chargerResultButton, 3, 4, 1, 1)
        self.chemClassesLabel = QtWidgets.QLabel(ChargerFichier)
        self.chemClassesLabel.setObjectName("chemClassesLabel")
        self.gridLayout.addWidget(self.chemClassesLabel, 1, 6, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 0, 1, 8)
        self.chargerClassesButton = QtWidgets.QPushButton(ChargerFichier)
        self.chargerClassesButton.setObjectName("chargerClassesButton")
        self.gridLayout.addWidget(self.chargerClassesButton, 1, 4, 1, 1)
        self.resultLabel = QtWidgets.QLabel(ChargerFichier)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.resultLabel.setFont(font)
        self.resultLabel.setObjectName("resultLabel")
        self.gridLayout.addWidget(self.resultLabel, 3, 2, 1, 1)
        self.orthoLabel = QtWidgets.QLabel(ChargerFichier)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.orthoLabel.setFont(font)
        self.orthoLabel.setObjectName("orthoLabel")
        self.gridLayout.addWidget(self.orthoLabel, 7, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ChargerFichier)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 9, 1, 1, 7)
        self.empriseLabel = QtWidgets.QLabel(ChargerFichier)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.empriseLabel.setFont(font)
        self.empriseLabel.setObjectName("empriseLabel")
        self.gridLayout.addWidget(self.empriseLabel, 5, 2, 1, 1)
        self.line = QtWidgets.QFrame(ChargerFichier)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 1, 7, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 2, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 4, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 6, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 8, 0, 1, 7)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 3, 7, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 6, 4, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 4, 4, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 2, 4, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 2, 6, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 4, 6, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem13, 6, 6, 1, 1)

        self.retranslateUi(ChargerFichier)
        self.buttonBox.accepted.connect(ChargerFichier.accept)
        self.buttonBox.rejected.connect(ChargerFichier.reject)
        QtCore.QMetaObject.connectSlotsByName(ChargerFichier)

    def retranslateUi(self, ChargerFichier):
        _translate = QtCore.QCoreApplication.translate
        ChargerFichier.setWindowTitle(_translate("ChargerFichier", "Chargement des fichiers"))
        self.classLabel.setText(_translate("ChargerFichier", "Description des classes"))
        self.cheminEmpriseLabel.setText(_translate("ChargerFichier", "[CheminEmprise]"))
        self.cheminOrthoLabel.setText(_translate("ChargerFichier", "[CheminOrtho]"))
        self.cheminResultLabel.setText(_translate("ChargerFichier", "[CheminResultats]"))
        self.chargerEmprButton.setText(_translate("ChargerFichier", "Charger..."))
        self.chargerOrthoButton.setText(_translate("ChargerFichier", "Charger..."))
        self.chargerResultButton.setText(_translate("ChargerFichier", "Charger..."))
        self.chemClassesLabel.setText(_translate("ChargerFichier", "[CheminClasses]"))
        self.chargerClassesButton.setText(_translate("ChargerFichier", "Charger..."))
        self.resultLabel.setText(_translate("ChargerFichier", "Résultat de classification"))
        self.orthoLabel.setText(_translate("ChargerFichier", "Orthoimage"))
        self.empriseLabel.setText(_translate("ChargerFichier", "Dossier des emprises"))

