# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Clémence\Documents\0-ENSG\1_TRONC_COMMUN\PROJET_INFO\1_ANALYSE\active-labelling\interface\classificationActive.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!
from choixClasse import *
from chargementFichiers import *
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InterfacePrincipale(object):
    def setupUi(self, InterfacePrincipale):
        InterfacePrincipale.setObjectName("InterfacePrincipale")
        InterfacePrincipale.resize(1120, 795)
        InterfacePrincipale.setMinimumSize(QtCore.QSize(900, 650))
        InterfacePrincipale.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.centralwidget = QtWidgets.QWidget(InterfacePrincipale)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.margxLabel = QtWidgets.QLabel(self.centralwidget)
        self.margxLabel.setObjectName("margxLabel")
        self.gridLayout.addWidget(self.margxLabel, 16, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 10, 2, 13)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 13, 10, 1, 13)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 22)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 1, 10, 1, 13)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 11, 10, 1, 13)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 4, 10, 1, 13)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 16, 3, 1, 1)
        self.margexBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.margexBrowser.setMaximumSize(QtCore.QSize(100, 30))
        self.margexBrowser.setObjectName("margexBrowser")
        self.gridLayout.addWidget(self.margexBrowser, 16, 5, 1, 1)
        self.questionLabel = QtWidgets.QLabel(self.centralwidget)
        self.questionLabel.setObjectName("questionLabel")
        self.gridLayout.addWidget(self.questionLabel, 3, 12, 1, 4)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 13, 3, 1)
        self.idLabel = QtWidgets.QLabel(self.centralwidget)
        self.idLabel.setObjectName("idLabel")
        self.gridLayout.addWidget(self.idLabel, 5, 14, 1, 1)
        self.classeLabel = QtWidgets.QLabel(self.centralwidget)
        self.classeLabel.setObjectName("classeLabel")
        self.gridLayout.addWidget(self.classeLabel, 6, 14, 1, 1)
        self.probaLabel = QtWidgets.QLabel(self.centralwidget)
        self.probaLabel.setObjectName("probaLabel")
        self.gridLayout.addWidget(self.probaLabel, 7, 14, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 16, 6, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 16, 8, 1, 1)
        self.margeyBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.margeyBrowser.setMaximumSize(QtCore.QSize(100, 30))
        self.margeyBrowser.setObjectName("margeyBrowser")
        self.gridLayout.addWidget(self.margeyBrowser, 16, 9, 1, 1)
        self.margeyLabel = QtWidgets.QLabel(self.centralwidget)
        self.margeyLabel.setObjectName("margeyLabel")
        self.gridLayout.addWidget(self.margeyLabel, 16, 7, 1, 1)
        self.yesButton = QtWidgets.QPushButton(self.centralwidget)
        self.yesButton.setObjectName("yesButton")
        self.gridLayout.addWidget(self.yesButton, 10, 11, 1, 12)
        self.noButton = QtWidgets.QPushButton(self.centralwidget)
        self.noButton.setObjectName("noButton")
        self.gridLayout.addWidget(self.noButton, 12, 11, 1, 12)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 16, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 17, 0, 1, 24)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 1, 0, 16, 1)
        self.entiteView = QtWidgets.QGraphicsView(self.centralwidget)
        self.entiteView.setMinimumSize(QtCore.QSize(500, 500))
        self.entiteView.setMaximumSize(QtCore.QSize(1000, 1000))
        self.entiteView.setObjectName("entiteView")
        self.gridLayout.addWidget(self.entiteView, 1, 1, 15, 9)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 5, 11, 3, 2)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 3, 11, 1, 1)
        self.borneLabel = QtWidgets.QLabel(self.centralwidget)
        self.borneLabel.setObjectName("borneLabel")
        self.gridLayout.addWidget(self.borneLabel, 15, 13, 1, 2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 15, 17, 2, 1)
        self.bornexValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.bornexValueLabel.setObjectName("bornexValueLabel")
        self.gridLayout.addWidget(self.bornexValueLabel, 15, 18, 1, 1)
        self.borneyValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.borneyValueLabel.setObjectName("borneyValueLabel")
        self.gridLayout.addWidget(self.borneyValueLabel, 16, 18, 1, 1)
        self.helpLogo = QtWidgets.QLabel(self.centralwidget)
        self.helpLogo.setMaximumSize(QtCore.QSize(20, 20))
        self.helpLogo.setText("")
        self.helpLogo.setPixmap(QtGui.QPixmap("question.png"))
        self.helpLogo.setScaledContents(True)
        self.helpLogo.setObjectName("helpLogo")
        self.gridLayout.addWidget(self.helpLogo, 6, 18, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 7, 18, 1, 3)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 5, 18, 1, 3)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 6, 19, 1, 2)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem17, 1, 23, 16, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem18, 15, 11, 2, 2)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem19, 15, 15, 2, 2)
        InterfacePrincipale.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(InterfacePrincipale)
        self.menuBar.setEnabled(True)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1120, 26))
        self.menuBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menuBar.setDefaultUp(False)
        self.menuBar.setObjectName("menuBar")
        self.fichierMenu = QtWidgets.QMenu(self.menuBar)
        self.fichierMenu.setObjectName("fichierMenu")
        InterfacePrincipale.setMenuBar(self.menuBar)
        self.statusbar = QtWidgets.QStatusBar(InterfacePrincipale)
        self.statusbar.setObjectName("statusbar")
        InterfacePrincipale.setStatusBar(self.statusbar)
        self.chargerAction = QtWidgets.QAction(InterfacePrincipale)
        self.chargerAction.setObjectName("chargerAction")
        #self.chargerAction.triggered
        self.fichierMenu.addAction(self.chargerAction)
        self.menuBar.addAction(self.fichierMenu.menuAction())

        self.retranslateUi(InterfacePrincipale)
        QtCore.QMetaObject.connectSlotsByName(InterfacePrincipale)

        #self.noButton.clicked.connect(QtCore.QCoreApplication.instance().quit)

    def retranslateUi(self, InterfacePrincipale):
        _translate = QtCore.QCoreApplication.translate
        InterfacePrincipale.setWindowTitle(_translate("InterfacePrincipale", "Classification active"))
        self.margxLabel.setText(_translate("InterfacePrincipale", "Marge verticale :"))
        self.margexBrowser.setHtml(_translate("InterfacePrincipale", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1.0</p></body></html>"))
        self.questionLabel.setText(_translate("InterfacePrincipale", "Cet objet est il bien classé ?"))
        self.idLabel.setText(_translate("InterfacePrincipale", "Identifiant de l\'objet"))
        self.classeLabel.setText(_translate("InterfacePrincipale", "Classe"))
        self.probaLabel.setText(_translate("InterfacePrincipale", "Probabilité"))
        self.margeyBrowser.setHtml(_translate("InterfacePrincipale", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1.0</p></body></html>"))
        self.margeyLabel.setText(_translate("InterfacePrincipale", "Marge horizontale :"))
        self.yesButton.setText(_translate("InterfacePrincipale", "OUI"))
        self.noButton.setText(_translate("InterfacePrincipale", "NON"))
        self.borneLabel.setText(_translate("InterfacePrincipale", "Bornes d\'affichage"))
        self.bornexValueLabel.setText(_translate("InterfacePrincipale", "(xmin, ymin)"))
        self.borneyValueLabel.setText(_translate("InterfacePrincipale", "(xmax, ymax)"))
        self.fichierMenu.setTitle(_translate("InterfacePrincipale", "Fichier"))
        self.chargerAction.setText(_translate("InterfacePrincipale", "Charger ..."))

#import images_rc
