# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Clémence\Documents\0-ENSG\1_TRONC_COMMUN\PROJET_INFO\1_ANALYSE\active-labelling\interface\classificationActive.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InterfacePrincipale(object):
    def setupUi(self, InterfacePrincipale):
        InterfacePrincipale.setObjectName("InterfacePrincipale")
        InterfacePrincipale.resize(800, 600)
        InterfacePrincipale.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.centralwidget = QtWidgets.QWidget(InterfacePrincipale)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 6, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 7, 1, 2, 8)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 6, 6, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 6)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 5, 8, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(20, 20))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Help/question.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 7, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 3, 3, 2)
        self.okButton = QtWidgets.QPushButton(self.centralwidget)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 9, 1, 1, 8)
        self.labelClasse = QtWidgets.QLabel(self.centralwidget)
        self.labelClasse.setObjectName("labelClasse")
        self.gridLayout.addWidget(self.labelClasse, 5, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem6, 3, 1, 1, 6)
        self.labelId = QtWidgets.QLabel(self.centralwidget)
        self.labelId.setObjectName("labelId")
        self.gridLayout.addWidget(self.labelId, 4, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 10, 1, 1, 8)
        self.entiteView = QtWidgets.QGraphicsView(self.centralwidget)
        self.entiteView.setMinimumSize(QtCore.QSize(500, 500))
        self.entiteView.setObjectName("entiteView")
        self.gridLayout.addWidget(self.entiteView, 0, 0, 13, 1)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 6, 1, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 5, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 4, 1, 1, 1)
        self.labelProb = QtWidgets.QLabel(self.centralwidget)
        self.labelProb.setObjectName("labelProb")
        self.gridLayout.addWidget(self.labelProb, 6, 5, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 12, 1, 1, 8)
        self.noButton = QtWidgets.QPushButton(self.centralwidget)
        self.noButton.setObjectName("noButton")
        self.gridLayout.addWidget(self.noButton, 11, 1, 1, 8)
        self.questionLabel = QtWidgets.QLabel(self.centralwidget)
        self.questionLabel.setObjectName("questionLabel")
        self.gridLayout.addWidget(self.questionLabel, 2, 5, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 4, 2, 3, 1)
    #    InterfacePrincipale.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(InterfacePrincipale)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        self.menuChager_fichier = QtWidgets.QMenu(self.menubar)
        self.menuChager_fichier.setObjectName("menuChager_fichier")
    #    InterfacePrincipale.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(InterfacePrincipale)
        self.statusbar.setObjectName("statusbar")
    #    InterfacePrincipale.setStatusBar(self.statusbar)
        self.actionCharger_fichiers = QtWidgets.QAction(InterfacePrincipale)
        self.actionCharger_fichiers.setIconVisibleInMenu(True)
        self.actionCharger_fichiers.setObjectName("actionCharger_fichiers")
        self.menuChager_fichier.addAction(self.actionCharger_fichiers)
        self.menubar.addAction(self.menuChager_fichier.menuAction())

        self.retranslateUi(InterfacePrincipale)
        QtCore.QMetaObject.connectSlotsByName(InterfacePrincipale)

    def retranslateUi(self, InterfacePrincipale):
        _translate = QtCore.QCoreApplication.translate
        InterfacePrincipale.setWindowTitle(_translate("InterfacePrincipale", "Interface de classification"))
        self.okButton.setText(_translate("InterfacePrincipale", "OUI"))
        self.labelClasse.setText(_translate("InterfacePrincipale", "Classe"))
        self.labelId.setText(_translate("InterfacePrincipale", "Identifiant de l\'objet"))
        self.labelProb.setText(_translate("InterfacePrincipale", "Probabilité"))
        self.noButton.setText(_translate("InterfacePrincipale", "NON"))
        self.questionLabel.setText(_translate("InterfacePrincipale", "Cet objet est il bien classé ?"))
        self.menuChager_fichier.setTitle(_translate("InterfacePrincipale", "Fichier"))
        self.actionCharger_fichiers.setText(_translate("InterfacePrincipale", "Charger ..."))

#import images_qrc
