# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Clémence\Documents\0-ENSG\1_TRONC_COMMUN\PROJET_INFO\1_ANALYSE\active-labelling\interface\classificationActive.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InterfacePrincipale(object):
    def setupUi(self, InterfacePrincipale):
        InterfacePrincipale.setObjectName("InterfacePrincipale")
        InterfacePrincipale.resize(1003, 679)
        InterfacePrincipale.setMinimumSize(QtCore.QSize(900, 650))
        InterfacePrincipale.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.centralwidget = QtWidgets.QWidget(InterfacePrincipale)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 11, 3, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 0))
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 20, 18, 1, 3)
        self.margeyLabel = QtWidgets.QLabel(self.centralwidget)
        self.margeyLabel.setObjectName("margeyLabel")
        self.gridLayout.addWidget(self.margeyLabel, 18, 6, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 20, 15, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 20, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 18, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 5, 13, 3, 1)
        self.noButton = QtWidgets.QPushButton(self.centralwidget)
        self.noButton.setObjectName("noButton")
        self.gridLayout.addWidget(self.noButton, 12, 11, 1, 12)
        self.probaLabel = QtWidgets.QLabel(self.centralwidget)
        self.probaLabel.setObjectName("probaLabel")
        self.gridLayout.addWidget(self.probaLabel, 7, 14, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 8, 10, 2, 13)
        self.idLabel = QtWidgets.QLabel(self.centralwidget)
        self.idLabel.setObjectName("idLabel")
        self.gridLayout.addWidget(self.idLabel, 5, 14, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 1, 10, 1, 13)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 18, 8, 1, 1)
        self.classeLabel = QtWidgets.QLabel(self.centralwidget)
        self.classeLabel.setObjectName("classeLabel")
        self.gridLayout.addWidget(self.classeLabel, 6, 14, 1, 1)
        self.yesButton = QtWidgets.QPushButton(self.centralwidget)
        self.yesButton.setObjectName("yesButton")
        self.gridLayout.addWidget(self.yesButton, 10, 11, 1, 12)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 11, 10, 1, 13)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 13, 10, 1, 13)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem9, 18, 5, 1, 1)
        self.questionLabel = QtWidgets.QLabel(self.centralwidget)
        self.questionLabel.setObjectName("questionLabel")
        self.gridLayout.addWidget(self.questionLabel, 3, 12, 1, 4)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 0, 0, 1, 24)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 19, 1, 1, 22)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 1, 23, 20, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 3, 11, 1, 1)
        self.helpLogo = QtWidgets.QLabel(self.centralwidget)
        self.helpLogo.setMaximumSize(QtCore.QSize(20, 20))
        self.helpLogo.setText("")
        self.helpLogo.setPixmap(QtGui.QPixmap("question.png"))
        self.helpLogo.setScaledContents(True)
        self.helpLogo.setObjectName("helpLogo")
        self.gridLayout.addWidget(self.helpLogo, 6, 18, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 15, 11, 4, 2)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem15, 4, 10, 1, 13)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 15, 15, 4, 2)
        self.entiteView = QtWidgets.QGraphicsView(self.centralwidget)
        self.entiteView.setMinimumSize(QtCore.QSize(500, 400))
        self.entiteView.setMaximumSize(QtCore.QSize(1500, 1500))
        self.entiteView.setObjectName("entiteView")
        self.gridLayout.addWidget(self.entiteView, 1, 1, 15, 9)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem17, 22, 0, 1, 24)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 18, 7, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 18, 4, 1, 1)
        self.borneyValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.borneyValueLabel.setObjectName("borneyValueLabel")
        self.gridLayout.addWidget(self.borneyValueLabel, 18, 18, 1, 1)
        self.bornexValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.bornexValueLabel.setObjectName("bornexValueLabel")
        self.gridLayout.addWidget(self.bornexValueLabel, 17, 18, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 17, 17, 2, 1)
        self.borneLabel = QtWidgets.QLabel(self.centralwidget)
        self.borneLabel.setObjectName("borneLabel")
        self.gridLayout.addWidget(self.borneLabel, 17, 14, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem18, 16, 1, 2, 9)
        self.margxLabel = QtWidgets.QLabel(self.centralwidget)
        self.margxLabel.setObjectName("margxLabel")
        self.gridLayout.addWidget(self.margxLabel, 18, 2, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem19, 20, 7, 1, 1)
        self.lancementButton = QtWidgets.QPushButton(self.centralwidget)
        self.lancementButton.setObjectName("lancementButton")
        self.gridLayout.addWidget(self.lancementButton, 20, 8, 1, 7)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem20, 7, 18, 1, 4)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem21, 6, 19, 1, 3)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem22, 5, 18, 1, 4)
        self.etatLabel = QtWidgets.QLabel(self.centralwidget)
        self.etatLabel.setObjectName("etatLabel")
        self.gridLayout.addWidget(self.etatLabel, 20, 2, 1, 5)
        InterfacePrincipale.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(InterfacePrincipale)
        self.menuBar.setEnabled(True)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1003, 26))
        self.menuBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menuBar.setDefaultUp(False)
        self.menuBar.setObjectName("menuBar")
        self.fichierMenu = QtWidgets.QMenu(self.menuBar)
        self.fichierMenu.setObjectName("fichierMenu")
        InterfacePrincipale.setMenuBar(self.menuBar)
        self.statusbar = QtWidgets.QStatusBar(InterfacePrincipale)
        self.statusbar.setObjectName("statusbar")
        InterfacePrincipale.setStatusBar(self.statusbar)
        self.chargerAction = QtWidgets.QAction(InterfacePrincipale)
        self.chargerAction.setObjectName("chargerAction")
        self.fichierMenu.addAction(self.chargerAction)
        self.menuBar.addAction(self.fichierMenu.menuAction())

        self.retranslateUi(InterfacePrincipale)
        QtCore.QMetaObject.connectSlotsByName(InterfacePrincipale)

    def retranslateUi(self, InterfacePrincipale):
        _translate = QtCore.QCoreApplication.translate
        InterfacePrincipale.setWindowTitle(_translate("InterfacePrincipale", "Classification active"))
        self.margeyLabel.setText(_translate("InterfacePrincipale", "Marge horizontale :"))
        self.noButton.setText(_translate("InterfacePrincipale", "NON"))
        self.probaLabel.setText(_translate("InterfacePrincipale", "Probabilité"))
        self.idLabel.setText(_translate("InterfacePrincipale", "Identifiant de l\'objet"))
        self.classeLabel.setText(_translate("InterfacePrincipale", "Classe"))
        self.yesButton.setText(_translate("InterfacePrincipale", "OUI"))
        self.questionLabel.setText(_translate("InterfacePrincipale", "Cet objet est il bien classé ?"))
        self.lineEdit.setText(_translate("InterfacePrincipale", "1.0"))
        self.lineEdit_2.setText(_translate("InterfacePrincipale", "1.0"))
        self.borneyValueLabel.setText(_translate("InterfacePrincipale", "(xmax, ymax)"))
        self.bornexValueLabel.setText(_translate("InterfacePrincipale", "(xmin, ymin)"))
        self.borneLabel.setText(_translate("InterfacePrincipale", "Bornes d\'affichage"))
        self.margxLabel.setText(_translate("InterfacePrincipale", "Marge verticale :"))
        self.lancementButton.setText(_translate("InterfacePrincipale", "Lancer la visualisation"))
        self.etatLabel.setText(_translate("InterfacePrincipale", "Charger les fichiers ..."))
        self.fichierMenu.setTitle(_translate("InterfacePrincipale", "Fichier"))
        self.chargerAction.setText(_translate("InterfacePrincipale", "Charger ..."))

#import images_rc
